id: 580e006600fd45b0b1cf4ffd9d825b01
initial_creation_type: ocr
source_metadata:
  volumes:
    0bf5254101334e06b9c34879dfc88722:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
